# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bbf3556814eceb94331e0d91791d9111"
name = "rental-date-picker"
handle = "rental-date-picker"
application_url = "https://lycos-jokes-emerging-nuclear.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dawn-customized-sandbox.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://lycos-jokes-emerging-nuclear.trycloudflare.com/auth/callback",
  "https://lycos-jokes-emerging-nuclear.trycloudflare.com/auth/shopify/callback",
  "https://lycos-jokes-emerging-nuclear.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
